.DEFAULT_GOAL := all

all:
	./mkeditorpacks all

darkradiant:
	./mkeditorpacks darkradiant

gtkradiant:
	./mkeditorpacks gtkradiant

jackhammer:
	./mkeditorpacks jackhammer

netradiant:
	./mkeditorpacks netradiant
