.DEFAULT_GOAL := all

all: darkradiant gtkradiant jackhammer netradiant

darkradiant:
	./mkeditorpacks --darkradiant

gtkradiant:
	./mkeditorpacks --gtkradiant

jackhammer:
	./mkeditorpacks --jackhammer

netradiant:
	./mkeditorpacks --netradiant
